services:
  sta:
    image: sta
    container_name: saludtech
    ports:
      - "5004:5000"
    environment:
      DB_URI: postgresql://postgres:postgres@database:5432/backend-sta-db
      BROKER_HOST: pulsar
    depends_on:
      database:
        condition: service_healthy
      pulsar:
        condition: service_healthy
  canonizacion:
    image: canonizacion
    container_name: canonizacion
    ports:
      - "5002:5002"
    environment:
      DB_URI: postgresql://postgres:postgres@database-canonizacion:5432/backend-canonizacion-db
      BROKER_HOST: pulsar
    depends_on:
      database-canonizacion:
        condition: service_healthy
      pulsar:
        condition: service_healthy

  sta3:
    image: sta3
    container_name: saludtech3
    ports:
      - "5003:5000"
    environment:
      DB_URI: postgresql://postgres:postgres@database3:5432/backend-sta3-db
      BROKER_HOST: pulsar
    depends_on:
      database3:
        condition: service_healthy
      pulsar:
        condition: service_healthy

  bff:
    image: bff
    container_name: backend-for-frontend
    ports:
      - "5001:5000"
    environment:
      BROKER_HOST: pulsar
      STA_HOST: sta
    depends_on:
      pulsar:
        condition: service_healthy


  notificaciones:
    image: notificaciones
    container_name: notificaciones
    environment:
      BROKER_HOST: pulsar
    depends_on:
      pulsar:
        condition: service_healthy

  pulsar:
    image: apachepulsar/pulsar:latest
    container_name: pulsar
    command: [ "bin/pulsar", "standalone" ]
    ports:
      - "6650:6650"  # Puerto para clientes Pulsar
      - "8080:8080"  # Puerto para la API REST de Pulsar
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/admin/v2/brokers/health" ]
      interval: 30s
      timeout: 10s
      retries: 5

  database:
    image: postgres
    container_name: postgres
    ports:
      - "5480:5432"
    environment:
      POSTGRES_DB: backend-sta-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 5s
      retries: 5

  database3:
    image: postgres
    container_name: postgres3
    ports:
      - "5481:5432"
    environment:
      POSTGRES_DB: backend-sta3-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 5s
      retries: 5

  database-canonizacion:
    image: postgres
    container_name: canonizacion-db
    ports:
      - "5482:5432"
    environment:
      POSTGRES_DB: backend-canonizacion-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 5s
      retries: 5