version: '3.8'

services:
  sta:
    image: sta
    container_name: saludtech
    ports:
      - "5000:5000"
    environment:
      DB_URI: postgresql://postgres:postgres@database:5432/backend-db
      BROKER_HOST: pulsar
    depends_on:
      database:
        condition: service_healthy
      pulsar:
        condition: service_healthy
    networks:
      - saludtech-network

  sta3:
    image: sta3
    container_name: saludtech3
    ports:
      - "5003:5003"
    environment:
      DB_URI: postgresql://postgres:postgres@database3:5431/backend-db
      BROKER_HOST: pulsar
    depends_on:
      database3:
        condition: service_healthy
      pulsar:
        condition: service_healthy
    networks:
      - saludtech-network

  notificaciones:
    image: notificaciones
    container_name: notificaciones
    environment:
      BROKER_HOST: pulsar
    depends_on:
      pulsar:
        condition: service_healthy
    networks:
      - saludtech-network

  pulsar:
    image: apachepulsar/pulsar:latest
    container_name: pulsar
    command: [ "bin/pulsar", "standalone" ]
    ports:
      - "6650:6650"  # Puerto para clientes Pulsar
      - "8080:8080"  # Puerto para la API REST de Pulsar
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/admin/v2/brokers/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - saludtech-network

  database:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: backend-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - saludtech-network

  database3:
    image: postgres
    container_name: postgres3
    ports:
      - "5431:5431"
    environment:
      POSTGRES_DB: backend-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 5s
      retries: 5
    volumes:
      - postgres3-data:/var/lib/postgresql/data
    networks:
      - saludtech-network

networks:
  saludtech-network:

volumes:
  postgres-data:
  postgres3-data: